{% set name = "gammapy" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2684cb14d2af6249c30e3afb791ce034d8c88a28672f691ce1f9e67e33259db8

build:
  number: 0
  entry_points:
    - gammapy = gammapy.scripts.main:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools_scm >=6.2
    - setuptools
    - pip !=22.1
    - cython
    - numpy >=1.26,<2.2
    - extension-helpers
  run:
    - python
    - setuptools
    - scipy >=1.13
    - astropy-base >=6.0
    - regions >=0.9
    - click >=9.0
    - pyyaml >=5.3
    - pydantic >=2.8
    - iminuit >=2.26.0
    - matplotlib-base >=3.8,<3.10

test:
  imports:
    - gammapy
    - gammapy.analysis
    - gammapy.astro
    - gammapy.astro.darkmatter
    - gammapy.astro.population
    - gammapy.astro.source
    - gammapy.catalog
    - gammapy.data
    - gammapy.irf
    - gammapy.maps
    - gammapy.modeling
    - gammapy.modeling.models
    - gammapy.scripts
    - gammapy.stats
    - gammapy.utils
    - gammapy.utils.coordinates
    - gammapy.utils.random
  commands:
    - gammapy --help

about:
  home: https://gammapy.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: A Python package for gamma-ray astronomy
  description: |
    Gammapy is an open-source Python package for gamma-ray astronomy built on Numpy and Astropy.
    It is a prototype for the Cherenkov Telescope Array (CTA) science tools,
    and can also be used to analyse data from existing gamma-ray telescopes.
  doc_url: https://docs.gammapy.org/
  dev_url: https://github.com/gammapy/gammapy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - adonath
    - registerrier
