{% set name = "gammapy" %}
{% set version = "0.7" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f30eef6efefb2829d55ceb4bab547011ae1e9fa0434cb5ab6042e4156f1ec6da" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 1
  entry_points:
    - gammapy = gammapy.scripts.main:cli
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - astropy >=1.3
  run:
    - python
    - numpy >=1.8
    - astropy >=1.3
    - regions
    - click

test:
  imports:
    - gammapy
    - gammapy.astro
    - gammapy.astro.population
    - gammapy.astro.source
    - gammapy.background
    - gammapy.catalog
    - gammapy.cube
    - gammapy.data
    - gammapy.datasets
    - gammapy.detect
    - gammapy.extern
    - gammapy.image
    - gammapy.image.models
    - gammapy.irf
    - gammapy.maps
    - gammapy.scripts
    - gammapy.spectrum
    - gammapy.stats
    - gammapy.time
    - gammapy.time.models
    - gammapy.utils
    - gammapy.utils.coordinates
    - gammapy.utils.distributions
    - gammapy.utils.root
  commands:
    - gammapy --help

about:
  home: http://gammapy.org/
  license: BSD 3-Clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: A Python package for gamma-ray astronomy
  description: |
    Gammapy is an open-source Python package for gamma-ray astronomy built on Numpy and Astropy. 
    It is a prototype for the Cherenkov Telescope Array (CTA) science tools,
    and can also be used to analyse data from existing gamma-ray telescopes.
  doc_url: http://docs.gammapy.org/
  dev_url: https://github.com/gammapy/gammapy

extra:
  recipe-maintainers:
    - mwcraig
    - bsipocz
    - cdeil
